/**
 * KYC Review Mock 数据
 */
import type { UserKYC, OCRResult, AgreementSignature } from "@/lib/kyc/types";

export const mockKYCRecords: UserKYC[] = [
  {
    id: "kyc-001",
    userId: "user-001",
    regionCode: "VN",
    kycLevel: "standard",
    status: "submitted",
    currentStep: 6,
    documentType: "id_card",
    documentFrontUrl: "/mock/id-front.jpg",
    documentBackUrl: "/mock/id-back.jpg",
    ocrData: {
      documentType: "id_card",
      fullName: "NGUYEN VAN A",
      idNumber: "123456789",
      dateOfBirth: "1990-05-15",
      nationality: "Vietnam",
      address: "123 Le Loi, District 1, Ho Chi Minh City",
      gender: "male",
      confidence: 0.94,
      rawData: {},
      userConfirmed: true,
    },
    ocrConfidence: 0.94,
    livenessPassed: true,
    livenessAttempts: 1,
    livenessVideoUrl: "/mock/liveness-001.mp4",
    // Vietnam doesn't require address proof
    experienceInfo: {
      employment: { employmentStatus: "employed", occupation: "Engineer", industry: "Technology", employer: "ABC Corp", position: "Senior Developer" },
      education: { highestLevel: "bachelor", fieldOfStudy: "Computer Science" },
      investmentExperience: { yearsOfExperience: "1_to_3", tradingFrequency: "weekly", productsTraded: ["forex", "stocks"], riskTolerance: "medium" },
      financialStatus: { annualIncome: "25k_to_50k", netWorth: "50k_to_100k", sourceOfFunds: "Salary", investmentObjectives: ["income", "growth"] },
      declarations: { isUSPerson: false, isPEP: false, isMilitary: false, isFinancialProfessional: false, hasCriminalRecord: false },
    },
    agreementsSigned: [
      { agreementId: "agr-001", agreementName: "Client Agreement", version: "v1.2", signedAt: "2026-05-07T10:00:00Z", signature: "NGUYEN VAN A", ipAddress: "192.168.1.1", userAgent: "Chrome" },
      { agreementId: "agr-002", agreementName: "Risk Disclosure", version: "v1.1", signedAt: "2026-05-07T10:01:00Z", signature: "NGUYEN VAN A", ipAddress: "192.168.1.1", userAgent: "Chrome" },
      { agreementId: "agr-003", agreementName: "Privacy Policy", version: "v1.0", signedAt: "2026-05-07T10:02:00Z", signature: "NGUYEN VAN A", ipAddress: "192.168.1.1", userAgent: "Chrome" },
    ],
    signatureType: "text",
    submittedAt: "2026-05-07T10:05:00Z",
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-05-07T10:05:00Z",
  },
  {
    id: "kyc-002",
    userId: "user-002",
    regionCode: "IN",
    kycLevel: "enhanced",
    status: "submitted",
    currentStep: 6,
    documentType: "passport",
    documentFrontUrl: "/mock/passport-front.jpg",
    ocrData: {
      documentType: "passport",
      fullName: "RAJESH KUMAR",
      idNumber: "A1234567",
      dateOfBirth: "1988-11-22",
      nationality: "India",
      confidence: 0.82,
      rawData: {},
      userConfirmed: true,
    },
    ocrConfidence: 0.82,
    livenessPassed: true,
    livenessAttempts: 2,
    livenessVideoUrl: "/mock/liveness-002.mp4",
    addressProofUrl: "/mock/address-proof-002.pdf",
    addressProofType: "bank_statement",
    experienceInfo: {
      employment: { employmentStatus: "self_employed", occupation: "Trader", industry: "Finance" },
      education: { highestLevel: "master", fieldOfStudy: "Finance" },
      investmentExperience: { yearsOfExperience: "3_to_5", tradingFrequency: "daily", productsTraded: ["forex", "stocks", "crypto"], riskTolerance: "high" },
      financialStatus: { annualIncome: "50k_to_100k", netWorth: "100k_to_500k", sourceOfFunds: "Trading", investmentObjectives: ["growth", "speculation"] },
      declarations: { isUSPerson: false, isPEP: false, isMilitary: false, isFinancialProfessional: true, hasCriminalRecord: false },
    },
    agreementsSigned: [
      { agreementId: "agr-001", agreementName: "Client Agreement", version: "v1.2", signedAt: "2026-05-08T09:00:00Z", signature: "Rajesh Kumar", ipAddress: "10.0.0.1", userAgent: "Firefox" },
      { agreementId: "agr-002", agreementName: "Risk Disclosure", version: "v1.1", signedAt: "2026-05-08T09:01:00Z", signature: "Rajesh Kumar", ipAddress: "10.0.0.1", userAgent: "Firefox" },
    ],
    signatureType: "text",
    submittedAt: "2026-05-08T09:05:00Z",
    createdAt: "2026-05-02T10:00:00Z",
    updatedAt: "2026-05-08T09:05:00Z",
  },
  {
    id: "kyc-003",
    userId: "user-003",
    regionCode: "VN",
    kycLevel: "standard",
    status: "submitted",
    currentStep: 4,
    documentType: "id_card",
    documentFrontUrl: "/mock/id-front-2.jpg",
    documentBackUrl: "/mock/id-back-2.jpg",
    ocrData: {
      documentType: "id_card",
      fullName: "TRAN THI B",
      idNumber: "987654321",
      dateOfBirth: "1995-08-03",
      nationality: "Vietnam",
      address: "456 Nguyen Hue, District 1, Ho Chi Minh City",
      gender: "female",
      confidence: 0.71,
      rawData: {},
      userConfirmed: true,
    },
    ocrConfidence: 0.71,
    livenessPassed: false,
    livenessAttempts: 3,
    // No address proof for VN
    experienceInfo: {
      employment: { employmentStatus: "student", occupation: "Student", industry: "Education" },
      education: { highestLevel: "bachelor", fieldOfStudy: "Business" },
      investmentExperience: { yearsOfExperience: "less_than_1", tradingFrequency: "rarely", productsTraded: ["forex"], riskTolerance: "low" },
      financialStatus: { annualIncome: "below_25k", netWorth: "below_50k", sourceOfFunds: "Family", investmentObjectives: ["income"] },
      declarations: { isUSPerson: false, isPEP: false, isMilitary: false, isFinancialProfessional: false, hasCriminalRecord: false },
    },
    agreementsSigned: [
      { agreementId: "agr-001", agreementName: "Client Agreement", version: "v1.2", signedAt: "2026-05-06T14:00:00Z", signature: "Tran Thi B", ipAddress: "172.16.0.1", userAgent: "Chrome" },
    ],
    signatureType: "handwritten",
    submittedAt: "2026-05-06T14:10:00Z",
    createdAt: "2026-05-03T12:00:00Z",
    updatedAt: "2026-05-06T14:10:00Z",
  },
  {
    id: "kyc-004",
    userId: "user-004",
    regionCode: "VN",
    kycLevel: "standard",
    status: "supplemental_required",
    currentStep: 2,
    documentType: "id_card",
    documentFrontUrl: "/mock/id-blurry.jpg",
    ocrData: {
      documentType: "id_card",
      fullName: "LE VAN C",
      idNumber: "112233445",
      dateOfBirth: "1985-03-10",
      nationality: "Vietnam",
      confidence: 0.55,
      rawData: {},
      userConfirmed: true,
    },
    ocrConfidence: 0.55,
    livenessPassed: true,
    livenessAttempts: 1,
    rejectionReason: "证件照片模糊，请重新上传清晰的证件照片",
    submittedAt: "2026-05-04T08:00:00Z",
    createdAt: "2026-05-04T07:00:00Z",
    updatedAt: "2026-05-04T09:00:00Z",
  },
  {
    id: "kyc-005",
    userId: "user-005",
    regionCode: "VN",
    kycLevel: "standard",
    status: "approved",
    currentStep: 6,
    documentType: "passport",
    documentFrontUrl: "/mock/passport-005.jpg",
    ocrData: {
      documentType: "passport",
      fullName: "PHAM THI D",
      idNumber: "C7654321",
      dateOfBirth: "1992-07-20",
      nationality: "Vietnam",
      confidence: 0.96,
      rawData: {},
      userConfirmed: true,
    },
    ocrConfidence: 0.96,
    livenessPassed: true,
    livenessAttempts: 1,
    agreementsSigned: [
      { agreementId: "agr-001", agreementName: "Client Agreement", version: "v1.2", signedAt: "2026-05-03T08:00:00Z", signature: "Pham Thi D", ipAddress: "10.0.0.5", userAgent: "Safari" },
      { agreementId: "agr-002", agreementName: "Risk Disclosure", version: "v1.1", signedAt: "2026-05-03T08:01:00Z", signature: "Pham Thi D", ipAddress: "10.0.0.5", userAgent: "Safari" },
      { agreementId: "agr-003", agreementName: "Privacy Policy", version: "v1.0", signedAt: "2026-05-03T08:02:00Z", signature: "Pham Thi D", ipAddress: "10.0.0.5", userAgent: "Safari" },
    ],
    signatureType: "text",
    submittedAt: "2026-05-03T08:05:00Z",
    reviewedAt: "2026-05-03T10:00:00Z",
    reviewedBy: "staff-001",
    createdAt: "2026-04-25T09:00:00Z",
    updatedAt: "2026-05-03T10:00:00Z",
  },
];

export const mockClientNames: Record<string, string> = {
  "user-001": "NGUYEN VAN A",
  "user-002": "RAJESH KUMAR",
  "user-003": "TRAN THI B",
  "user-004": "LE VAN C",
  "user-005": "PHAM THI D",
};
