import type { ApprovalItem } from "@/types/approval";

const now = Date.now();
const h = (n: number) => new Date(now + n * 3_600_000).toISOString();
const ago = (n: number) => new Date(now - n * 3_600_000).toISOString();

export const MOCK_APPROVALS: ApprovalItem[] = [
  // ── KYC ────────────────────────────────────────────────────────────────
  {
    id: "apr-kyc-001",
    type: "kyc",
    sourceId: "case-002",
    detailUrl: "/crm/clm/cases/case-002",
    userId: "u-001", userUid: "18428392", userName: "Rajesh Kumar", userCountry: "IN",
    subject: "Identity Document",
    riskLevel: "medium",
    status: "in_review",
    slaDueAt: ago(0.5),          // 30 min overdue
    createdAt: ago(25),
    canInlineApprove: false,
  },
  {
    id: "apr-kyc-002",
    type: "kyc",
    sourceId: "case-003",
    detailUrl: "/crm/clm/cases/case-003",
    userId: "u-002", userUid: "10028393", userName: "Nguyen Van A", userCountry: "VN",
    subject: "Proof of Address",
    riskLevel: "low",
    status: "pending",
    slaDueAt: h(0.4),            // 24 min left — urgent
    createdAt: ago(23),
    canInlineApprove: false,
  },
  {
    id: "apr-kyc-003",
    type: "kyc",
    sourceId: "case-004",
    detailUrl: "/crm/clm/cases/case-004",
    userId: "u-003", userUid: "10028394", userName: "Carlos Romero", userCountry: "MX",
    subject: "Identity Document",
    riskLevel: "high",
    status: "pending",
    slaDueAt: h(2),
    createdAt: ago(22),
    canInlineApprove: false,
  },
  {
    id: "apr-kyc-004",
    type: "kyc",
    sourceId: "case-005",
    detailUrl: "/crm/clm/cases/case-005",
    userId: "u-004", userUid: "10028395", userName: "Elena Petrova", userCountry: "RU",
    subject: "Source of Wealth",
    riskLevel: "critical",
    riskFlags: ["AML hit", "PEP"],
    status: "pending",
    slaDueAt: h(3),
    createdAt: ago(21),
    canInlineApprove: false,
  },
  {
    id: "apr-kyc-005",
    type: "kyc",
    sourceId: "case-006",
    detailUrl: "/crm/clm/cases/case-006",
    userId: "u-005", userUid: "10028396", userName: "Ahmed Al-Rashid", userCountry: "AE",
    subject: "Identity Document",
    riskLevel: "low",
    status: "pending",
    slaDueAt: h(6),
    createdAt: ago(18),
    canInlineApprove: false,
  },
  {
    id: "apr-kyc-006",
    type: "kyc",
    sourceId: "case-007",
    detailUrl: "/crm/clm/cases/case-007",
    userId: "u-006", userUid: "10028397", userName: "Wei Zhang", userCountry: "CN",
    subject: "Liveness Check",
    riskLevel: "medium",
    status: "pending",
    slaDueAt: h(8),
    createdAt: ago(16),
    canInlineApprove: false,
  },
  {
    id: "apr-kyc-007",
    type: "kyc",
    sourceId: "case-008",
    detailUrl: "/crm/clm/cases/case-008",
    userId: "u-007", userUid: "10028398", userName: "Sophie Martin", userCountry: "FR",
    subject: "Proof of Address",
    riskLevel: "low",
    status: "pending",
    slaDueAt: h(12),
    createdAt: ago(12),
    canInlineApprove: false,
  },
  {
    id: "apr-kyc-008",
    type: "kyc",
    sourceId: "case-009",
    detailUrl: "/crm/clm/cases/case-009",
    userId: "u-008", userUid: "10028399", userName: "Lucas Silva", userCountry: "BR",
    subject: "Video Verification",
    riskLevel: "high",
    riskFlags: ["Large withdrawal pending"],
    status: "in_review",
    slaDueAt: h(1.5),
    createdAt: ago(22),
    canInlineApprove: false,
  },

  // ── Deposits ────────────────────────────────────────────────────────────
  {
    id: "apr-dep-001",
    type: "deposit",
    sourceId: "dep-001",
    detailUrl: "/crm/funds/deposits",
    userId: "u-009", userUid: "10028401", userName: "James Okafor", userCountry: "NG",
    subject: "Bank Transfer · $8,200",
    amount: 8200, currency: "USD",
    riskLevel: "low",
    status: "pending",
    slaDueAt: ago(1.2),          // overdue
    createdAt: ago(26),
    canInlineApprove: true,
  },
  {
    id: "apr-dep-002",
    type: "deposit",
    sourceId: "dep-002",
    detailUrl: "/crm/funds/deposits",
    userId: "u-010", userUid: "10028402", userName: "Maria Garcia", userCountry: "ES",
    subject: "Card Deposit · $3,500",
    amount: 3500, currency: "USD",
    riskLevel: "low",
    status: "pending",
    slaDueAt: h(0.3),            // 18 min — urgent
    createdAt: ago(24),
    canInlineApprove: true,
  },
  {
    id: "apr-dep-003",
    type: "deposit",
    sourceId: "dep-003",
    detailUrl: "/crm/funds/deposits",
    userId: "u-011", userUid: "10028403", userName: "Yuki Tanaka", userCountry: "JP",
    subject: "Crypto · 12,400 USDT",
    amount: 12400, currency: "USDT",
    riskLevel: "medium",
    riskFlags: ["New wallet address"],
    status: "pending",
    slaDueAt: h(4),
    createdAt: ago(20),
    canInlineApprove: true,
  },
  {
    id: "apr-dep-004",
    type: "deposit",
    sourceId: "dep-004",
    detailUrl: "/crm/funds/deposits",
    userId: "u-012", userUid: "10028404", userName: "Ivan Petrov", userCountry: "RU",
    subject: "Bank Transfer · $72,000",
    amount: 72000, currency: "USD",
    riskLevel: "high",
    riskFlags: ["Exceeds $50k threshold", "Sanctioned region"],
    status: "pending",
    slaDueAt: h(2),
    createdAt: ago(22),
    canInlineApprove: false,     // > $50k → force review
  },
  {
    id: "apr-dep-005",
    type: "deposit",
    sourceId: "dep-005",
    detailUrl: "/crm/funds/deposits",
    userId: "u-013", userUid: "10028405", userName: "Amira Hassan", userCountry: "EG",
    subject: "E-Wallet · $1,800",
    amount: 1800, currency: "USD",
    riskLevel: "low",
    status: "on_hold",
    slaDueAt: h(10),
    createdAt: ago(14),
    canInlineApprove: true,
  },

  // ── Withdrawals ─────────────────────────────────────────────────────────
  {
    id: "apr-wd-001",
    type: "withdrawal",
    sourceId: "wd-001",
    detailUrl: "/crm/funds/withdrawal-review",
    userId: "u-014", userUid: "10028411", userName: "Thomas Müller", userCountry: "DE",
    subject: "Bank Transfer · $6,500",
    amount: 6500, currency: "USD",
    riskLevel: "low",
    status: "pending",
    slaDueAt: ago(0.8),          // overdue
    createdAt: ago(28),
    canInlineApprove: true,
  },
  {
    id: "apr-wd-002",
    type: "withdrawal",
    sourceId: "wd-002",
    detailUrl: "/crm/funds/withdrawal-review",
    userId: "u-015", userUid: "10028412", userName: "Priya Sharma", userCountry: "IN",
    subject: "Crypto · 4,200 USDT",
    amount: 4200, currency: "USDT",
    riskLevel: "medium",
    riskFlags: ["First crypto withdrawal"],
    status: "pending",
    slaDueAt: h(0.7),            // 42 min — urgent
    createdAt: ago(23),
    canInlineApprove: true,
  },
  {
    id: "apr-wd-003",
    type: "withdrawal",
    sourceId: "wd-003",
    detailUrl: "/crm/funds/withdrawal-review",
    userId: "u-016", userUid: "10028413", userName: "Oliver Chen", userCountry: "SG",
    subject: "Bank Transfer · $15,000",
    amount: 15000, currency: "USD",
    riskLevel: "high",
    riskFlags: ["Exceeds $10k threshold"],
    status: "pending",
    slaDueAt: h(3),
    createdAt: ago(21),
    canInlineApprove: false,     // > $10k → force review
  },
  {
    id: "apr-wd-004",
    type: "withdrawal",
    sourceId: "wd-004",
    detailUrl: "/crm/funds/withdrawal-review",
    userId: "u-017", userUid: "10028414", userName: "Fatima Al-Zahra", userCountry: "MA",
    subject: "E-Wallet · $2,100",
    amount: 2100, currency: "USD",
    riskLevel: "low",
    status: "pending",
    slaDueAt: h(7),
    createdAt: ago(17),
    canInlineApprove: true,
  },
  {
    id: "apr-wd-005",
    type: "withdrawal",
    sourceId: "wd-005",
    detailUrl: "/crm/funds/withdrawal-review",
    userId: "u-018", userUid: "10028415", userName: "Dmitri Volkov", userCountry: "RU",
    subject: "Crypto · 9,800 USDT",
    amount: 9800, currency: "USDT",
    riskLevel: "medium",
    status: "on_hold",
    slaDueAt: h(5),
    createdAt: ago(19),
    canInlineApprove: true,
  },
];
